import 'package:hive/hive.dart';
part 'message.g.dart'; // Generated by build_runner

@HiveType(typeId: 0)
class Message extends HiveObject {
  @HiveField(0)
  String id;

  @HiveField(1)
  String senderId;

  @HiveField(2)
  String receiverId;

  @HiveField(3)
  String type; // 'text', 'image'

  @HiveField(4)
  String payload; // encrypted base64

  @HiveField(5)
  int timestamp;

  @HiveField(6)
  int ttl;

  @HiveField(7)
  int hops;

  @HiveField(8)
  bool delivered;

  @HiveField(9)
  int priorityIndex; // 0=normal, 1=important, 2=critical

  Message({
    required this.id,
    required this.senderId,
    required this.receiverId,
    required this.type,
    required this.payload,
    required this.timestamp,
    this.ttl = 3600,
    this.hops = 0,
    this.delivered = false,
    this.priorityIndex = 0,
  });

  factory Message.fromJson(Map<String, dynamic> json) {
    return Message(
      id: (json['id'] as String?) ?? '',
      senderId: (json['senderId'] as String?) ?? '',
      receiverId: (json['receiverId'] as String?) ?? '',
      type: (json['type'] as String?) ?? 'text',
      payload: (json['payload'] as String?) ?? '',
      timestamp: (json['timestamp'] as num?)?.toInt() ?? DateTime.now().millisecondsSinceEpoch,
      ttl: (json['ttl'] as num?)?.toInt() ?? 3600,
      hops: (json['hops'] as num?)?.toInt() ?? 0,
      delivered: (json['delivered'] as bool?) ?? false,
      priorityIndex: (json['priorityIndex'] as num?)?.toInt() ?? 0,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'senderId': senderId,
      'receiverId': receiverId,
      'type': type,
      'payload': payload,
      'timestamp': timestamp,
      'ttl': ttl,
      'hops': hops,
      'delivered': delivered,
      'priorityIndex': priorityIndex,
    };
  }
}
